import Head from "next/head";
import Intro from "@/components/Intro";
import About from "@/components/About";
import Header from "@/components/Header";
import Skills from "@/components/Skills";
import { useEffect } from "react";
import Portfolio from "@/components/Portfolio";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";

export default function Home() {
  useEffect(() => {
    const observer = new IntersectionObserver((entries, opts) => {
      entries.forEach((entry) => {
        entry.target.classList.toggle("visible", entry.isIntersecting);
      });
    });
    observer.observe(document.querySelector("div.skill-container"));
    observer.observe(document.querySelector("section#about"));
    observer.observe(document.querySelector("section#portfolio"));
    observer.observe(document.querySelector("section#contact"));
  }, []);
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Intro />
      <About />
      <Skills />
      <Portfolio />
      <Contact />
      <Footer />
    </>
  );
}
